version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongodb-fullstack
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongodb:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    command: mongod --auth
    networks:
      - fullstack

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    container_name: mongo-express-fullstack
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - fullstack

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: backend-fullstack
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/mongodb-fullstack
    restart: unless-stopped
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fullstack

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    container_name: frontend-fullstack
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge